"""Added base or metadata distinction for files

Revision ID: 27bf6f7e4b35
Revises: 9b4f33cfff3d
Create Date: 2025-10-14 02:04:06.787103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27bf6f7e4b35'
down_revision: Union[str, Sequence[str], None] = '9b4f33cfff3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('file_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'file_type')
    # ### end Alembic commands ###
