"""Initial migration

Revision ID: 9b4f33cfff3d
Revises: 
Create Date: 2025-10-13 23:06:13.682400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4f33cfff3d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'uploads', 'workspaces', ['workspace_id'], ['workspace_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.drop_column('uploads', 'workspace_id')
    # ### end Alembic commands ###
